[build]
    command = "cd frontend && rm -rf node_modules && npm install --legacy-peer-deps && npm run build"
    publish = "frontend/build"
[build.environment]
  NODE_VERSION = "16"  # Matches react-qr-reader's requirements
  NPM_FLAGS = "--legacy-peer-deps"